### ISSUE TITLE
Commit emails are Github password

### ISSUE THREAD

**Issue by kdhira** [kblincoe/VisualGit_SE701#48]
When committing using VisualGit, it fills in the author with your Github username, and more importantly the **email field with your Github password**. This has a vast security implication as any commits made through VisualGit that are pushed github will have your credentials shown.

![image](https://user-images.githubusercontent.com/21208233/37443502-70eb2596-2871-11e8-8b0e-792a7a8be791.png)

Here, my username is kevos (a dub account I don't really use) and the wtf701please is my password.

**Comment by kdhira** [comment]
@softeng-701 @kblincoe this is pretty important

**Comment by kblincoe** [comment]
Is this an issue in the original code or specific to your private repo?

**Comment by kdhira** [comment]
I've been working off my fork (as per the fork/clone workflow discussed), however I haven't made any changes from upstream, and I pull from upstream just before realising this issue

**Comment by kblincoe** [comment]
It may have been introduced by someone else in your repo (and you should post this issue in your private repo), but please test first on the code in this repo. If it is from the original code, I will post your issue in all of the other private repos.

**Comment by kdhira** [comment]
Oh I just realised that this should be in the VisualGit_SE701_1 issue section. And yes that could be the case (when I referred to upstream, I meant VisualGit_SE701_1)

**Comment by kdhira** [comment]
Sorry, when I glossed over the the _1 repo issues, someone had already brought it up and approved by the TAs. Not sure how I missed it and also post the issue here instead of the _1 repo, must have misclicked. I guess this issue can be closed/deleted

**Comment by kblincoe** [comment]
ok
